### ISSUE TITLE
failed build

### ISSUE THREAD

**Issue by 3cb** [KaOS-Community-Packages/atom-editor#1]
I tried to install version 1.0 from KCP and the build failed with this message:

Installing package-generator@0.39.0 ✗
Unable to download https://www.atom.io/api/packages/package-generator/versions/0.39.0/tarball: getaddrinfo ENOTFOUND

When I put that address into my browser the files download just fine.  So I'm not sure what the problem is.

**Comment by demmm** [comment]
Paste the full log, including the call used to start the build.

**Comment by m-c-b** [comment]
The build failed on a different package this time.

Initiated from Octopi(right-click>install):

Cloning into 'atom-editor'...
remote: Counting objects: 75, done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 75 (delta 3), reused 0 (delta 0), pack-reused 63
Unpacking objects: 100% (75/75), done.
Checking connectivity... done.
Do you want to edit PKGBUILD? [Y/n] n
==> Making package: atom-editor 1.0.0-1 (Wed Jul  1 11:38:39 EDT 2015)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Downloading v1.0.0.tar.gz...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   117    0   117    0     0    884      0 --:--:-- --:--:-- --:--:--   886
100 4189k  100 4189k    0     0  3613k      0  0:00:01  0:00:01 --:--:-- 4103k
==> Validating source files with md5sums...
    v1.0.0.tar.gz ... Passed
==> Extracting sources...
  -> Extracting v1.0.0.tar.gz with bsdtar
==> Starting prepare()...
==> Starting build()...
Node: v0.12.4
npm: v2.10.1
Installing build modules...
Installing apm...
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
Installing modules ✓
Installing atom-dark-syntax@0.27.0 ✓
Installing atom-dark-ui@0.49.0 ✓
Installing atom-light-syntax@0.28.0 ✓
Installing atom-light-ui@0.41.0 ✓
Installing base16-tomorrow-dark-theme@0.26.0 ✓
Installing base16-tomorrow-light-theme@0.9.0 ✓
Installing one-dark-ui@0.9.1 ✓
Installing one-dark-syntax@0.7.1 ✓
Installing one-light-syntax@0.7.0 ✓
Installing one-light-ui@0.9.1 ✓
Installing solarized-dark-syntax@0.35.0 ✓                                                                                                                                                                                                     
Installing solarized-light-syntax@0.21.0 ✓                                                                                                                                                                                                    
Installing archive-view@0.58.0 ✓                                                                                                                                                                                                              
Installing autocomplete-atom-api@0.9.0 ✓                                                                                                                                                                                                      
Installing autocomplete-css@0.8.0 ✓                                                                                                                                                                                                           
Installing autocomplete-html@0.7.2 ✓                                                                                                                                                                                                          
Installing autocomplete-plus@2.17.4 ✓                                                                                                                                                                                                         
Installing autocomplete-snippets@1.7.0 ✓                                                                                                                                                                                                      
Installing autoflow@0.25.0 ✓                                                                                                                                                                                                                  
Installing autosave@0.21.0 ✓                                                                                                                                                                                                                  
Installing background-tips@0.25.0 ✓                                                                                                                                                                                                           
Installing bookmarks@0.35.0 ✓                                                                                                                                                                                                                 
Installing bracket-matcher@0.76.0 ✓
Installing command-palette@0.36.0 ✓
Installing deprecation-cop@0.52.0 ✓
Installing dev-live-reload@0.46.0 ✓
Installing encoding-selector@0.20.0 ✓
Installing exception-reporting@0.25.0 ✓
Installing find-and-replace@0.174.0 ✓
Installing fuzzy-finder@0.87.0 ✓
Installing git-diff@0.55.0 ✓
Installing go-to-line@0.30.0 ✓
Installing grammar-selector@0.47.0 ✓
Installing image-view@0.54.0 ✓
Installing incompatible-packages@0.24.0 ✓
Installing keybinding-resolver@0.33.0 ✓
Installing link@0.30.0 ✓
Installing markdown-preview@0.150.0 ✓
Installing metrics@0.51.0 ✓
Installing notifications@0.56.0 ✓
Installing open-on-github@0.37.0 ✓
Installing package-generator@0.39.0 ✓
Installing release-notes@0.53.0 ✓
Installing settings-view@0.208.0 ✓
Installing snippets@0.95.0 ✓
Installing spell-check@0.59.0 ✓
Installing status-bar@0.74.0 ✓
Installing styleguide@0.44.0 ✓
Installing symbols-view@0.99.0 ✓
Installing tabs@0.81.0 ✓
Installing timecop@0.31.0 ✓
Installing tree-view@0.172.0 ✓
Installing update-package-dependencies@0.10.0 ✗
Unable to download https://www.atom.io/api/packages/update-package-dependencies/versions/0.10.0/tarball: getaddrinfo ENOTFOUND
==> ERROR: A failure occurred in build().
    Aborting...
exit status 2

Press any key to continue...

**Comment by Adurol** [comment]
Got it to build with 42dd13ebe8763e9246eb3f603e38964e36c23042. Closing issue.
