### ISSUE TITLE
Should be removed?

### ISSUE THREAD

**Issue by demmm** [KaOS-Community-Packages/atom-editor#2]
Atom from source is now in the apps repo, it is build to conflict and replace this bin version, so a user can't install this one any longer.
Should this bin version stay up?  If so then this one should add the conflicts with apps/atom.
Or remove from KCP?

**Comment by Astate** [comment]
i think its can be removed from KCP

**Comment by demmm** [comment]
OK, 3 for removing (plus I think no need to keep it either), so removing it is.
